datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: "Prometheus"
        type: prometheus
        uid: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitor:9090/
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
      - name: "Alertmanager"
        type: alertmanager
        uid: alertmanager
        url: http://prometheus-kube-prometheus-alertmanager.monitor:9093/
        access: proxy
        isDefault: false
        jsonData:
          handleGrafanaManagedAlerts: false
          implementation: prometheus

grafana:
  dashboardsConfigMaps:
    default: grafana-dashboard

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards