replicaCount: 1

image:
  repository: moshelederman/project-stars
  pullPolicy: Always
  tag: latest

mysql:
  image: mysql:8.0
  rootPassword: example
  database: testdb
  user: user
  password: example

service:
  type: LoadBalancer
  port: 5000

env:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"

initSQL:
  images:
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQpArEoEZ1VHxhyDql-WVesjhL7fvjTHu51g&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvu6HM8akCU-hEUkKwKyKkHwSKlle4sFBng&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYI-PhTZDz-MQDRy1-og36KLCmUPxYC1VYZQ&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXe5cneDUCl4Q2zyo0GzSSLZt3RrsQjFF_jg&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfdzIu068pNBUDj3ko7Gkn228JhWoyEP3oNg&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTzHrtew1BUXh7F8GnCMcC3WorcDEFbGmC0w&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRitHhHKJ9l_Il9DS-XT4V_gPcUV6woMU1VfA&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0w5CoquU-vjC3hHLbHqqzpCUjajmnQ3njyA&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTunuv7Ntr7YxZKE8_mZFgV2-lsVnJZ4-Cb8g&s"
    - "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLogIQHovcRhTiSzwbmMD9a3rfbi60UOf52A&s"
