replicaCount: 1

image:
  repository: moshelederman/project-stars
  pullPolicy: Always
  tag: latest

service:
  type: LoadBalancer
  port: 5000

mysql:
  rootPassword: example
  database: testdb
  user: user
  password: example
  host: mysql
  port: 3306

initSQL:
  enabled: true

resources: {}