apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.rootPassword }}"
  MYSQL_DATABASE: "{{ .Values.mysql.database }}"
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.password }}"
  MYSQL_HOST: "{{ .Values.mysql.host }}"
  MYSQL_PORT: "{{ .Values.mysql.port }}"