apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project-stars.fullname" . }}-mysql-init-sql
data:
  init.sql: |
{{- range $index, $url := .Values.initSQL.images }}
    INSERT INTO images (image_url) VALUES ("{{$url}}");
{{- end }}
    -- שאר פקודות ה-SQL
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }};
    USE {{ .Values.mysql.database }};
    CREATE TABLE IF NOT EXISTS images (
       id_images INT AUTO_INCREMENT PRIMARY KEY,
       image_url VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS visitors (
      id INT AUTO_INCREMENT PRIMARY KEY,
      visit_count INT NOT NULL DEFAULT 0
    );

    INSERT INTO visitors (visit_count) VALUES (0);

    CREATE USER IF NOT EXISTS '{{ .Values.mysql.user }}'@'%' IDENTIFIED BY '{{ .Values.mysql.password }}';

    GRANT ALL PRIVILEGES ON {{ .Values.mysql.database }}.* TO '{{ .Values.mysql.user }}'@'%';
    FLUSH PRIVILEGES;
