apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-stars.fullname" . }}-app
  labels:
    app: {{ include "project-stars.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "project-stars.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "project-stars.name" . }}
    spec:
      containers:
        - name: {{ include "project-stars.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.env.MYSQL_HOST }}
            - name: MYSQL_PORT
              value: {{ .Values.env.MYSQL_PORT }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "project-stars.fullname" . }}-mysql-secret
                  key: MYSQL_PASSWORD
