apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: project-stars
  template:
    metadata:
      labels:
        app: project-stars
    spec:
      containers:
      - name: project-stars
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: app-config