apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS testdb;
    USE testdb;
    CREATE TABLE IF NOT EXISTS images (
       id_images INT AUTO_INCREMENT PRIMARY KEY,
       image_url VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS visitors (
      id INT AUTO_INCREMENT PRIMARY KEY,
      visit_count INT NOT NULL DEFAULT 0
    );

    INSERT INTO images (image_url) VALUES    
    ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfdzIu068pNBUDj3ko7Gkn228JhWoyEP3oNg&s"),
    ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTzHrtew1BUXh7F8GnCMcC3WorcDEFbGmC0w&s"),
    ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRitHhHKJ9l_Il9DS-XT4V_gPcUV6woMU1VfA&s"),
    ("https://www.hayadan.org.il/images/content3/2015/04/westerlund-composite.jpg"),
    ("https://www.bareket-astro.com/cache/advportfoliopro/m20_1468248544_jpg_6cf38f95032c758d38d9eec813644605.jpg"),
    ("https://www.space.gov.il/sites/default/files/main_image_star-forming_region_carina_nircam_final-5mb%20%281%29.jpg"),
    ("https://www.space.gov.il/sites/default/files/646px-Stephan%27s_Quintet_Hubble_2009.full_denoise_1.jpg),
    ("https://apod.nasa.gov/apod/image/2503/NGC772Comet_Bax_1080_annotated.jpg"),
    ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLogIQHovcRhTiSzwbmMD9a3rfbi60UOf52A&s");

    INSERT INTO visitors (visit_count) VALUES (0);