apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-stars.fullname" . }}-mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
