apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: your-app-servicemonitor
  namespace: monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: project-stars
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http
  namespaceSelector:
    matchNames:
      - default