apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
  labels:
    app: project-stars
spec:
  selector:
    app: project-stars
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}