apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: your-app-servicemonitor
spec:
  selector:
    matchLabels:
      app: your-app
  endpoints:
    - port: prometheus-metrics
      interval: 15s