apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-stars.fullname" . }}-service
spec:
  selector:
    app: {{ include "project-stars.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
