apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: project-stars
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}